#Use existing docker image as a base
FROM  tensorflow/tensorflow:latest-gpu-py3
LABEL maintainer="peterpirogtf@gmail.com"

#Download and install dependencies
RUN export python=python3
RUN apt-get update -y
RUN apt-get install --no-install-recommends -y libgl1-mesa-dev
RUN apt-get install --no-install-recommends -y rsync
RUN apt-get install --no-install-recommends -y apt-utils
RUN apt-get autoremove -y

#Upgrade pip and setuptools
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install --upgrade setuptools
#RUN pip install torch===1.7.0+cu110 torchvision===0.8.1+cu110 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html


RUN pip install gym[atari]
RUN pip install box2d
RUN pip install gym[box2d]
RUN pip install scikit-learn

RUN pip install modin
RUN pip install -U ray[all]
RUN ray install-nightly

RUN pip install argparse
#install Gaussian Process Framework
RUN pip install GPy

#RUN TENSORBOARD SERVER
#RUN tensorboard --logdir=/root/ray_results --bind_all

# Container start command
CMD ["/bin/bash"]


#command to build new image:
#sudo docker build -t peterpirogtf/ray_tf2:latest .

#How to push docker image to hub

#login by:
# docker login
# docker push peterpirogtf/ray_tf2:latest
#https://stackoverflow.com/questions/41984399/denied-requested-access-to-the-resource-is-denied-docker

#https://github.com/ray-project/ray/blob/master/doc/source/rllib-training.rst

# sudo docker run --cpus 8 --gpus all -it -p 8265:8265 --rm peterpirogtf/ray_tf2 rllib train --run=TD3 --env=BipedalWalker-v3
# sudo docker run --cpus 8 --gpus all -it -p 8265:8265 --rm peterpirogtf/ray_tf2 rllib train --run=TD3 --env=BipedalWalkerHardcore-v3

# sudo docker run  --cpus 8 --gpus all -it -p 8265:8265 --rm peterpirogtf/ray_tf2 rllib train --run=TD3 --env=BipedalWalkerHardcore-v3  --ray-num-gpus 1 --eager

#sudo docker run -v `pwd`:`pwd` -w `pwd` -it -p 8265:8265 --rm peterpirogtf/ray_tf2 rllib train --run=PPO --env=CartPole-v0 --checkpoint-freq 3

#sudo docker run -v `./`:`pwd` -w `pwd` -it -p 8265:8265 --rm peterpirogtf/ray_tf2 rllib train --run=PPO --env=CartPole-v0 --checkpoint-freq 3 --eager

#sudo docker run -v ~/PycharmProjects/Ray_tests:`pwd` -w `pwd` -it -p 8265:8265 --rm peterpirogtf/ray_tf2 rllib train --run=PPO --env=CartPole-v0 --checkpoint-freq 3 --eager --export-formats model

#rllib train --env=PongDeterministic-v4 --run=A2C --config '{"num_workers": 2, "monitor": true}'
#rllib train --run DQN --env CartPole-v0 --eager --config '{"num_workers": 2, "monitor": true, "num_gpus" : 1}'
#rllib train --run=TD3 --env=BipedalWalkerHardcore-v3 --eager --ray-num-gpus 1 --checkpoint-freq 10 --export-formats model


#MULTI PLATFORM
#https://docs.docker.com/buildx/working-with-buildx/
#HOW TO INSTALL DOCKER ON RASPBERRY: https://phoenixnap.com/kb/docker-on-raspberry-pi
#docker buildx build  --platform linux/amd64,linux/arm64,linux/arm/v7 --push -t peterpirogtf/ray_tf2:latest .
